on: [push]

name: ci

jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      EXE_EXT: ${{ contains(matrix.os, 'windows') && '.exe' || '' }}

    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM (windows only)
      if: runner.os == 'Windows'
      run: choco install llvm

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly'

    - name: Install dep
      run: |
        cargo install --force cargo-make
        makers install_dep

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Check fmt
      run: cargo fmt -- --check

    - name: Run all tests
      run: makers test

    - name: generate coverage
      run: makers coverage-ci
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: coverage.lcov
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build optimized binary
      run: cargo build --release --locked

    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.os }}
        path: target/release/intmax-node${{ env.EXE_EXT }}