on: [push]

name: Integration

jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-lastest, macOS-latest, windows-latest]

    env:
      EXE_EXT: ${{ contains(matrix.os, 'windows') && '.exe' || '' }}

    steps:
    - name: Install LLVM (windows only)
      if: runner.os == 'Windows'
      run: choco install llvm

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly'

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Check fmt
      run: cargo fmt -- --check

    - name: Run all tests
      run: cargo test --all

    - name: Build optimized binary
      run: cargo build --release --locked

    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.os }}
        path: target/release/intmax-node${{ env.EXE_EXT }}